"use client";

import { useRef, useState, useTransition } from "react";
import { Bot, Loader2, Send, User2, Wrench, AlertTriangle, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { cn } from "@/lib/utils";
import type { Agent } from "@/lib/schemas/agent";

type Message = {
  role: "user" | "assistant";
  content: string;
  meta?: Reply; // attached when the assistant message was generated by us
};

type RetrievedChunk = {
  id: string;
  content: string;
  content_type: string;
  score: number;
  source: string;
};

type Reply = {
  reply_text: string;
  confidence: number;
  confidence_breakdown: {
    retrieval: number;
    intent: number;
    groundedness: number;
    consistency: number;
  };
  detected_stage: string;
  detected_intent: string;
  detected_intents: string[];
  suggested_tool: string;
  tool_args: Record<string, unknown>;
  reasoning: string;
  retrieved_chunk_ids: string[];
  reply_log_id: string;
  below_threshold: boolean;
  retrieved_chunks: RetrievedChunk[];
  prompt_preview: string;
};

export function PlaygroundChat({ agent }: { agent: Agent }) {
  const [history, setHistory] = useState<Message[]>([]);
  const [input, setInput] = useState("");
  const [pending, startTransition] = useTransition();
  const [lastReply, setLastReply] = useState<Reply | null>(null);
  const [error, setError] = useState<string | null>(null);
  const chatBottomRef = useRef<HTMLDivElement>(null);

  function onSend(e?: React.FormEvent) {
    e?.preventDefault();
    const trigger = input.trim();
    if (!trigger) return;
    setError(null);
    setInput("");
    const nextHistory: Message[] = [...history, { role: "user", content: trigger }];
    setHistory(nextHistory);

    startTransition(async () => {
      const res = await fetch(`/api/v1/agents/${agent.id}/reply`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          trigger_message: trigger,
          history: nextHistory.slice(0, -1).map((m) => ({
            role: m.role,
            content: m.content,
          })),
        }),
      });
      const body = await res.json();
      if (!res.ok) {
        setError(body?.error?.message ?? "generation failed");
        return;
      }
      const reply = body.data as Reply;
      setLastReply(reply);
      setHistory([
        ...nextHistory,
        {
          role: "assistant",
          content: reply.reply_text,
          meta: reply,
        },
      ]);
      requestAnimationFrame(() => chatBottomRef.current?.scrollIntoView({ behavior: "smooth" }));
    });
  }

  function reset() {
    setHistory([]);
    setLastReply(null);
    setError(null);
  }

  return (
    <div className="grid flex-1 grid-cols-[minmax(0,1fr)_420px] overflow-hidden">
      {/* Chat column */}
      <div className="flex flex-col overflow-hidden border-r">
        <div className="flex items-center justify-between border-b px-6 py-3">
          <div className="text-sm">
            <span className="font-medium">Playground</span>
            <span className="ml-2 text-muted-foreground">
              Stage inference + retrieval + grounded draft
            </span>
          </div>
          <Button variant="ghost" size="sm" onClick={reset} disabled={history.length === 0}>
            <Trash2 className="mr-2 h-4 w-4" /> Reset
          </Button>
        </div>

        <div className="flex-1 overflow-y-auto p-6">
          <div className="mx-auto flex max-w-2xl flex-col gap-4">
            {history.length === 0 ? (
              <div className="rounded-lg border border-dashed p-6 text-center text-sm text-muted-foreground">
                Paste a message from a prospect to see Tiberius draft a reply.
                <br />
                Use the right panel to inspect retrieved chunks and confidence.
              </div>
            ) : null}
            {history.map((m, i) => (
              <MessageBubble key={i} message={m} />
            ))}
            {pending ? (
              <div className="flex items-center gap-2 text-sm text-muted-foreground">
                <Loader2 className="h-4 w-4 animate-spin" /> drafting…
              </div>
            ) : null}
            {error ? (
              <div className="rounded-md border border-red-500/40 bg-red-500/10 p-3 text-sm text-red-700 dark:text-red-400">
                {error}
              </div>
            ) : null}
            <div ref={chatBottomRef} />
          </div>
        </div>

        <form onSubmit={onSend} className="border-t p-4">
          <div className="mx-auto flex max-w-2xl items-end gap-2">
            <Textarea
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter" && !e.shiftKey) {
                  e.preventDefault();
                  onSend();
                }
              }}
              rows={2}
              placeholder="Hey, what does Ivy charge? We do about $50M/month on USDC."
              disabled={pending}
            />
            <Button type="submit" disabled={pending || !input.trim()}>
              <Send className="h-4 w-4" />
            </Button>
          </div>
        </form>
      </div>

      {/* Debug column */}
      <aside className="flex flex-col overflow-hidden bg-sidebar/50">
        {lastReply ? (
          <DebugPanel reply={lastReply} />
        ) : (
          <div className="flex flex-1 items-center justify-center p-6 text-sm text-muted-foreground">
            Debug view appears here after the first reply.
          </div>
        )}
      </aside>
    </div>
  );
}

function MessageBubble({ message }: { message: Message }) {
  const isAssistant = message.role === "assistant";
  const meta = message.meta;
  return (
    <div className={cn("flex gap-3", isAssistant ? "flex-row" : "flex-row-reverse")}>
      <div
        className={cn(
          "flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-xs",
          isAssistant
            ? "bg-sidebar-primary text-sidebar-primary-foreground"
            : "bg-muted text-muted-foreground",
        )}
      >
        {isAssistant ? <Bot className="h-4 w-4" /> : <User2 className="h-4 w-4" />}
      </div>
      <div className={cn("flex max-w-[80%] flex-col gap-2", isAssistant ? "" : "items-end")}>
        <Card className={cn("px-3.5 py-2 text-sm")}>
          <div className="whitespace-pre-wrap">{message.content}</div>
          {meta ? (
            <div className="mt-2 flex flex-wrap items-center gap-1.5 border-t pt-2 text-xs text-muted-foreground">
              <Badge variant="outline" className="text-[10px]">
                stage: {meta.detected_stage}
              </Badge>
              <Badge variant="outline" className="text-[10px]">
                intent: {meta.detected_intent}
              </Badge>
              <Badge variant="outline" className="text-[10px]">
                conf: {meta.confidence.toFixed(2)}
              </Badge>
              {meta.suggested_tool !== "none" ? (
                <Badge
                  variant={meta.below_threshold ? "destructive" : "secondary"}
                  className="text-[10px]"
                >
                  <Wrench className="mr-1 h-3 w-3" />
                  {meta.suggested_tool}
                </Badge>
              ) : null}
              {meta.below_threshold ? (
                <Badge variant="destructive" className="text-[10px]">
                  <AlertTriangle className="mr-1 h-3 w-3" />
                  below threshold
                </Badge>
              ) : null}
            </div>
          ) : null}
        </Card>
      </div>
    </div>
  );
}

function ConfidenceBar({ label, value }: { label: string; value: number }) {
  const pct = Math.round(value * 100);
  const color =
    value >= 0.7 ? "bg-emerald-500" : value >= 0.5 ? "bg-amber-500" : "bg-red-500";
  return (
    <div className="flex flex-col gap-1">
      <div className="flex justify-between text-xs">
        <span className="text-muted-foreground">{label}</span>
        <span className="font-mono">{pct}%</span>
      </div>
      <div className="h-1.5 overflow-hidden rounded-full bg-muted">
        <div className={cn("h-full transition-all", color)} style={{ width: `${pct}%` }} />
      </div>
    </div>
  );
}

function DebugPanel({ reply }: { reply: Reply }) {
  return (
    <Tabs defaultValue="retrieved" className="flex flex-1 flex-col gap-2 overflow-hidden">
      <div className="border-b px-4 pt-4">
        <TabsList className="w-full">
          <TabsTrigger value="retrieved" className="flex-1">
            Retrieved
          </TabsTrigger>
          <TabsTrigger value="confidence" className="flex-1">
            Confidence
          </TabsTrigger>
          <TabsTrigger value="prompt" className="flex-1">
            Prompt
          </TabsTrigger>
          <TabsTrigger value="reasoning" className="flex-1">
            Reasoning
          </TabsTrigger>
        </TabsList>
      </div>

      <TabsContent value="retrieved" className="flex-1 overflow-y-auto px-4 pb-4">
        <div className="mb-2 text-xs text-muted-foreground">
          {reply.retrieved_chunks.length} chunks reranked. Lower = less relevant.
        </div>
        <div className="flex flex-col gap-2">
          {reply.retrieved_chunks.map((c, i) => (
            <Card key={c.id} className="p-3">
              <div className="mb-1 flex items-center justify-between text-xs">
                <div className="flex items-center gap-1">
                  <span className="font-mono text-muted-foreground">#{i + 1}</span>
                  <Badge variant="secondary" className="text-[10px]">
                    {c.content_type}
                  </Badge>
                  <Badge variant="outline" className="text-[10px]">
                    {c.source}
                  </Badge>
                </div>
                <span className="font-mono text-muted-foreground">
                  {c.score.toFixed(3)}
                </span>
              </div>
              <div className="line-clamp-3 text-xs leading-relaxed text-muted-foreground">
                {c.content}
              </div>
            </Card>
          ))}
        </div>
      </TabsContent>

      <TabsContent value="confidence" className="flex-1 overflow-y-auto px-4 pb-4">
        <Card className="p-4">
          <div className="mb-3 flex items-center justify-between">
            <span className="text-sm font-medium">Overall</span>
            <span className="font-mono text-lg">{reply.confidence.toFixed(2)}</span>
          </div>
          <Separator className="my-2" />
          <div className="flex flex-col gap-3 pt-2">
            <ConfidenceBar label="retrieval (25%)" value={reply.confidence_breakdown.retrieval} />
            <ConfidenceBar label="intent (20%)" value={reply.confidence_breakdown.intent} />
            <ConfidenceBar
              label="groundedness (40%)"
              value={reply.confidence_breakdown.groundedness}
            />
            <ConfidenceBar
              label="consistency (15%)"
              value={reply.confidence_breakdown.consistency}
            />
          </div>
          {reply.below_threshold ? (
            <div className="mt-4 rounded-md border border-red-500/40 bg-red-500/10 p-3 text-xs text-red-700 dark:text-red-400">
              Below agent threshold — tool forced to{" "}
              <code className="rounded bg-background px-1">flag_for_review</code>.
              {reply.tool_args?.review_reason ? (
                <div className="mt-1">{String(reply.tool_args.review_reason)}</div>
              ) : null}
            </div>
          ) : null}
        </Card>
      </TabsContent>

      <TabsContent value="prompt" className="flex-1 overflow-hidden px-4 pb-4">
        <Card className="h-full overflow-hidden p-0">
          <pre className="h-full overflow-auto whitespace-pre-wrap break-words p-3 font-mono text-[10px] leading-relaxed">
            {reply.prompt_preview}
          </pre>
        </Card>
      </TabsContent>

      <TabsContent value="reasoning" className="flex-1 overflow-y-auto px-4 pb-4">
        <Card className="p-4">
          <div className="mb-3">
            <div className="text-xs font-medium uppercase tracking-wider text-muted-foreground">
              Model reasoning
            </div>
            <p className="mt-1 text-sm">{reply.reasoning}</p>
          </div>
          <Separator />
          <div className="mt-3">
            <div className="text-xs font-medium uppercase tracking-wider text-muted-foreground">
              Suggested tool
            </div>
            <p className="mt-1 font-mono text-sm">{reply.suggested_tool}</p>
            {Object.keys(reply.tool_args ?? {}).length ? (
              <pre className="mt-1 overflow-auto rounded bg-muted p-2 text-[11px]">
                {JSON.stringify(reply.tool_args, null, 2)}
              </pre>
            ) : null}
          </div>
          <Separator className="my-3" />
          <div>
            <div className="text-xs font-medium uppercase tracking-wider text-muted-foreground">
              Detected
            </div>
            <p className="mt-1 text-xs">
              stage <code className="rounded bg-muted px-1">{reply.detected_stage}</code>{" "}
              · intents{" "}
              <code className="rounded bg-muted px-1">
                {reply.detected_intents.join(", ")}
              </code>
            </p>
          </div>
        </Card>
      </TabsContent>
    </Tabs>
  );
}
