import { readFile, writeFile, mkdir, readdir, copyFile, rm } from "node:fs/promises";

const SRC_DIR = "data/conversations";
const TRAIN_DIR = "data/conversations/training";
const EVAL_DIR = "data/conversations/eval";
const SPLIT_MD = "data/conversations/SPLIT.md";

// Hand-picked stratification. Rationale lives in SPLIT.md.
// Picks aim for: outcome diversity, scenario coverage (pricing / competitor /
// scheduling-positive / hard-factual), and variety of conversation shapes.
const EVAL_IDS = [
  "convo_01", // fit_mismatch — competitor (Mollie) + qualification/license edge case
  "convo_07", // no_response — cold outreach that never got a reply
  "convo_09", // call_booked — clean scheduling-positive (GBP Open Banking → book)
  "convo_17", // fit_mismatch — stage-shift dynamic (lead ready → sales pulls back)
  "convo_18", // fit_mismatch — scheduled → stalled (different failure mode)
];

type Convo = {
  id: string;
  messages: unknown[];
  outcome: string;
  stages_covered: string[];
  notes?: string | null;
};

async function main() {
  const files = (await readdir(SRC_DIR)).filter((f) => /^convo_\d{2}\.json$/.test(f));
  if (files.length !== 20) {
    throw new Error(`Expected 20 convo files in ${SRC_DIR}, found ${files.length}`);
  }

  const convos: Convo[] = [];
  for (const f of files) {
    const j = JSON.parse(await readFile(`${SRC_DIR}/${f}`, "utf-8")) as Convo;
    convos.push(j);
  }

  const evalSet = new Set(EVAL_IDS);
  for (const id of EVAL_IDS) {
    if (!convos.find((c) => c.id === id)) throw new Error(`Missing eval convo: ${id}`);
  }

  // Reset target dirs
  await rm(TRAIN_DIR, { recursive: true, force: true });
  await rm(EVAL_DIR, { recursive: true, force: true });
  await mkdir(TRAIN_DIR, { recursive: true });
  await mkdir(EVAL_DIR, { recursive: true });

  const byBucket = { training: [] as Convo[], eval: [] as Convo[] };
  for (const c of convos) {
    const bucket = evalSet.has(c.id) ? "eval" : "training";
    byBucket[bucket].push(c);
    const dst = bucket === "eval" ? EVAL_DIR : TRAIN_DIR;
    await copyFile(`${SRC_DIR}/${c.id}.json`, `${dst}/${c.id}.json`);
  }

  // Build SPLIT.md
  const tally = (rows: Convo[]) =>
    rows.reduce<Record<string, number>>((acc, c) => {
      acc[c.outcome] = (acc[c.outcome] ?? 0) + 1;
      return acc;
    }, {});
  const trainTally = tally(byBucket.training);
  const evalTally = tally(byBucket.eval);

  const rationale = {
    convo_01:
      "fit_mismatch + competitor mention (Mollie 'we are already in talks with Mollie'); covers qualification/license edge case. Closest proxy for competitor-objection legacy scenario.",
    convo_07:
      "no_response — cold outreach with zero lead engagement. Covers a failure mode absent from the other picks.",
    convo_09:
      "call_booked — clean scheduling-positive flow: lead asks 'Open Banking in GBP?', sales answers, call booked. Covers scheduling-positive legacy scenario.",
    convo_17:
      "fit_mismatch with mid-conversation stage-shift (lead ready to book → sales pulls back after realizing scope mismatch). Tests stage/intent detection nuance.",
    convo_18:
      "fit_mismatch — scheduled → stalled path, different shape from convo_01 and convo_17. Gives model a second 'went south' example to generalize from.",
  } satisfies Record<(typeof EVAL_IDS)[number], string>;

  const md = `# Train/Eval Split — Ivy Pre-Discovery Conversations

Generated by \`scripts/split-conversations.ts\`. Rationale is hand-picked; re-run the script to regenerate files, but the picks below are deterministic (see \`EVAL_IDS\` in the script).

## Totals
- Training: ${byBucket.training.length}
- Eval:     ${byBucket.eval.length}

## Outcome distribution

| Outcome | Training | Eval |
|---|---|---|
${[...new Set([...Object.keys(trainTally), ...Object.keys(evalTally)])]
  .sort()
  .map((o) => `| ${o} | ${trainTally[o] ?? 0} | ${evalTally[o] ?? 0} |`)
  .join("\n")}

## Eval picks — rationale

${EVAL_IDS.map((id) => {
  const c = convos.find((x) => x.id === id)!;
  return `### \`${id}\` — outcome=${c.outcome}, stages=[${c.stages_covered.join(",")}]
${rationale[id as keyof typeof rationale]}

Notes from extraction: ${c.notes ?? "—"}`;
}).join("\n\n")}

## Training picks (everything else)

${byBucket.training
  .map((c) => `- \`${c.id}\` — ${c.outcome}, ${c.messages.length} msgs`)
  .join("\n")}

## Known caveats
- **0 \`disqualified\` outcomes** in the dataset — the miniModel categorised everything license/fit-refusal-shaped as \`fit_mismatch\` rather than \`disqualified\`. Stratification rule relaxed accordingly; \`fit_mismatch\` is used as the proxy.
- **Extraction has noise** — spot-checked convo_01 and saw one role misattribution (msg 3: lead reply labelled as \`sales\`/Ruben). Good enough for retrieval/chunk quality; will re-check during Phase B gold-reply extraction.
- **Legacy scenario coverage**: competitor ✓ (convo_01 Mollie), scheduling-positive ✓ (convo_09), fit-shift ✓ (convo_17). Pricing-cold and hard-factual-unknown not obvious in the eval picks — if \`scripts/build-eval-cases.ts\` fails to match them, the synthetic legacy cases stay with \`synthetic:true\`.
`;

  await writeFile(SPLIT_MD, md);
  console.log(`Split written:`);
  console.log(`  ${TRAIN_DIR}/  (${byBucket.training.length} files)`);
  console.log(`  ${EVAL_DIR}/   (${byBucket.eval.length} files)`);
  console.log(`  ${SPLIT_MD}`);
  console.log(`\nOutcome distribution:`);
  console.log(
    `  training: ${Object.entries(trainTally)
      .map(([k, v]) => `${k}=${v}`)
      .join(", ")}`,
  );
  console.log(
    `  eval:     ${Object.entries(evalTally)
      .map(([k, v]) => `${k}=${v}`)
      .join(", ")}`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
